{
    "An exception of category 'Configuration' occurred while\n   [0] Processing run: 1 lumi: 1 event: 1\n   [1] Running path 'validation_step'\n   [2] Calling event method for module MixingModule/'mix'\nException Message:\nRootInputFileSequence::readOneSpecified(): no input files specified for secondary input source.\n": [
        "200.0",
        "25206.0"
    ],
    "An exception of category 'FileOpenError' occurred while\n   [0] Calling InputSource::readFile_\n   [1] Opening DQM Root file\n   [2] Calling StorageFactory::open()\n   [3] Calling File::sysopen()\nException Message:\nFailed to open the file 'step1_inDQM.root'\nInput file file:step1_inDQM.root was not found, could not be opened, or is corrupted.\n   Additional Info:\n      [a] open() failed with system error 'No such file or directory' (error code 2)\n": [
        "521.0"
    ],
    "An exception of category 'LogicError' occurred while\n   [0] Processing run: 1\n   [1] Calling global beginRun for module Pythia8HadronizerFilter/'generator'\nException Message:\n::getByToken: An attempt was made to read a Run product before endRun() was called.\nThe index of the token was 1.\n": [
        "513.0",
        "523.0",
        "528.0",
        "516.0",
        "519.0",
        "525.0"
    ],
    "An exception of category 'OutputOpenError' occurred while\n   [0] Processing run: 1\n   [1] Calling global beginRun for module ExternalLHEProducer/'externalLHEProducer'\nException Message:\nUnable to open script output file cmsgrid_final.lhe (errno=2, No such file or directory).\n": [
        "526.0",
        "512.0",
        "522.0",
        "515.0",
        "518.0",
        "529.0"
    ]
}